'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.34014
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KinectCameraSample.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Failed to write screenshot to {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public ReadOnly Property FailedScreenshotStatusTextFormat() As String
            Get
                Return ResourceManager.GetString("FailedScreenshotStatusTextFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  No ready Kinect found! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public ReadOnly Property NoSensorStatusText() As String
            Get
                Return ResourceManager.GetString("NoSensorStatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Running に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public ReadOnly Property RunningStatusText() As String
            Get
                Return ResourceManager.GetString("RunningStatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Saved screenshot to {0} に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public ReadOnly Property SavedScreenshotStatusTextFormat() As String
            Get
                Return ResourceManager.GetString("SavedScreenshotStatusTextFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Kinect not available! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Public ReadOnly Property SensorNotAvailableStatusText() As String
            Get
                Return ResourceManager.GetString("SensorNotAvailableStatusText", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
